# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.stackedWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(120, 0, 591, 291))
        self.label.setStyleSheet("background-image: url(:/newPrefix/social-network.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(230, 340, 411, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.rbDirected = QtWidgets.QRadioButton(self.page)
        self.rbDirected.setGeometry(QtCore.QRect(270, 380, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.rbDirected.setFont(font)
        self.rbDirected.setObjectName("rbDirected")
        self.rbUndirected = QtWidgets.QRadioButton(self.page)
        self.rbUndirected.setGeometry(QtCore.QRect(450, 380, 141, 17))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.rbUndirected.setFont(font)
        self.rbUndirected.setObjectName("rbUndirected")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setGeometry(QtCore.QRect(230, 420, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setGeometry(QtCore.QRect(520, 420, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.graphInfoBtn = QtWidgets.QPushButton(self.page)
        self.graphInfoBtn.setGeometry(QtCore.QRect(380, 480, 101, 31))
        self.graphInfoBtn.setObjectName("graphInfoBtn")
        self.stackedWidget.addWidget(self.page)




        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.graphMatrix = QtWidgets.QTableWidget(self.page_2)
        self.graphMatrix.setGeometry(QtCore.QRect(150, 90, 491, 351))
        self.graphMatrix.setAutoFillBackground(False)
        self.graphMatrix.setStyleSheet("font: 12pt \"Calibri\";\n"
"border-color: rgb(255, 255, 255);")
        self.graphMatrix.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphMatrix.setFrameShadow(QtWidgets.QFrame.Sunken)

        self.graphMatrix.setRowCount(1)
        self.graphMatrix.setColumnCount(1)
        self.graphMatrix.setObjectName("graphMatrix")

        item = QtWidgets.QTableWidgetItem()
        self.graphMatrix.setVerticalHeaderItem(0, item)


        item = QtWidgets.QTableWidgetItem()
        self.graphMatrix.setHorizontalHeaderItem(0, item)

        item = QtWidgets.QTableWidgetItem()
        self.graphMatrix.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)

        self.graphMatrix.horizontalHeader().setVisible(True)
        self.graphMatrix.horizontalHeader().setCascadingSectionResizes(True)
        self.graphMatrix.horizontalHeader().setDefaultSectionSize(50)
        self.graphMatrix.horizontalHeader().setMinimumSectionSize(23)
        self.graphMatrix.horizontalHeader().setSortIndicatorShown(False)
        self.graphMatrix.horizontalHeader().setStretchLastSection(False)
        self.graphMatrix.verticalHeader().setVisible(True)
        self.graphMatrix.verticalHeader().setDefaultSectionSize(30)
        self.graphMatrix.verticalHeader().setSortIndicatorShown(False)
        self.graphMatrix.verticalHeader().setStretchLastSection(False)

        self.makeGraphBtn = QtWidgets.QPushButton(self.page_2)
        self.makeGraphBtn.setGeometry(QtCore.QRect(340, 520, 101, 31))
        self.makeGraphBtn.setObjectName("makeGraphBtn")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Do you want to draw a Directed Graph or a Undirected Graph?"))
        self.rbDirected.setText(_translate("MainWindow", "Directed Graph"))
        self.rbUndirected.setText(_translate("MainWindow", "Undirected Graph"))
        self.label_4.setText(_translate("MainWindow", "What is the order of your graph?"))
        self.graphInfoBtn.setText(_translate("MainWindow", "OK"))
        self.graphMatrix.setSortingEnabled(True)
        item = self.graphMatrix.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "A"))
        item = self.graphMatrix.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "A"))
        __sortingEnabled = self.graphMatrix.isSortingEnabled()
        self.graphMatrix.setSortingEnabled(False)
        item = self.graphMatrix.item(0, 0)
        item.setText(_translate("MainWindow", "0"))
        self.graphMatrix.setSortingEnabled(__sortingEnabled)
        self.makeGraphBtn.setText(_translate("MainWindow", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
